/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b88c4b47-f241-4447-8485-9a4c703bb2fb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_D5eycOyGe",
    "aws_user_pools_web_client_id": "1p6dkjujjhegb9ml3v0kfmttqq",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "memorialsiteff04753a871945f28d774c40429a973934133-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
